## CSV Files

In [2]:
import requests
import pandas as pd
from io import StringIO

url = "https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv"
headers = {"User-Agent": "Mozilla/5.0"}  # Proper dictionary with key-value
req = requests.get(url, headers=headers)

data = StringIO(req.text)
df = pd.read_csv(data)

print(df.head())

         Date   AAPL.Open   AAPL.High    AAPL.Low  AAPL.Close  AAPL.Volume  \
0  2015-02-17  127.489998  128.880005  126.919998  127.830002     63152400
1  2015-02-18  127.629997  128.779999  127.449997  128.720001     44891700
2  2015-02-19  128.479996  129.029999  128.330002  128.449997     37362400
3  2015-02-20  128.619995  129.500000  128.050003  129.500000     48948400
4  2015-02-23  130.020004  133.000000  129.660004  133.000000     70974100

   AAPL.Adjusted          dn        mavg          up   direction
0     122.905254  106.741052  117.927667  129.114281  Increasing
1     123.760965  107.842423  118.940333  130.038244  Increasing
2     123.501363  108.894245  119.889167  130.884089  Decreasing
3     124.510914  109.785449  120.763500  131.741551  Increasing
4     127.876074  110.372516  121.720167  133.067817  Increasing

In [12]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno')

,name,release_year,rating,votes,genre
sno,,,,,
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [8]:
##if column name becomes 1st row,write header=1

In [13]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',usecols=['sno','name','rating','votes'])

                            name  rating     votes
sno
m0    10 things i hate about you     6.9   62847.0
m1    1492: conquest of paradise     6.2   10421.0
m2                    15 minutes     6.1   25854.0
m3         2001: a space odyssey     8.4  163227.0
m4                       48 hrs.     6.9   22289.0
...                          ...     ...       ...
m612                    watchmen     7.8  135229.0
m613                         xxx     5.6   53505.0
m614                       x-men     7.4  122149.0
m615          young frankenstein     8.0   57618.0
m616                   zulu dawn     6.4    1911.0

[617 rows x 3 columns]

In [14]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',usecols=['sno','name','rating','votes'],skiprows=[0,1])

                       name  rating     votes
sno
m2               15 minutes     6.1   25854.0
m3    2001: a space odyssey     8.4  163227.0
m4                  48 hrs.     6.9   22289.0
m5        the fifth element     7.5  133756.0
m6                      8mm     6.3   48212.0
...                     ...     ...       ...
m612               watchmen     7.8  135229.0
m613                    xxx     5.6   53505.0
m614                  x-men     7.4  122149.0
m615     young frankenstein     8.0   57618.0
m616              zulu dawn     6.4    1911.0

[615 rows x 3 columns]

In [15]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',usecols=['sno','name','rating','votes'],nrows=100)

                                     name  rating   votes
sno
m0             10 things i hate about you     6.9   62847
m1             1492: conquest of paradise     6.2   10421
m2                             15 minutes     6.1   25854
m3                  2001: a space odyssey     8.4  163227
m4                                48 hrs.     6.9   22289
..                                    ...     ...     ...
m95                           i am legend     7.1  156084
m96                    invaders from mars     6.4    2115
m97                      independence day     6.6  151698
m98    indiana jones and the last crusade     8.3  174947
m99  indiana jones and the temple of doom     7.5  112054

[100 rows x 3 columns]

In [16]:
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv"

# Example 1: Default UTF-8 encoding
df_utf8 = pd.read_csv(url, encoding="utf-8")
print(df_utf8.head())

# Example 2: For demonstration, forcing Latin-1 encoding
df_latin1 = pd.read_csv(url, encoding="latin1")
print(df_latin1.head())

         Date   AAPL.Open   AAPL.High    AAPL.Low  AAPL.Close  AAPL.Volume  \
0  2015-02-17  127.489998  128.880005  126.919998  127.830002     63152400
1  2015-02-18  127.629997  128.779999  127.449997  128.720001     44891700
2  2015-02-19  128.479996  129.029999  128.330002  128.449997     37362400
3  2015-02-20  128.619995  129.500000  128.050003  129.500000     48948400
4  2015-02-23  130.020004  133.000000  129.660004  133.000000     70974100

   AAPL.Adjusted          dn        mavg          up   direction
0     122.905254  106.741052  117.927667  129.114281  Increasing
1     123.760965  107.842423  118.940333  130.038244  Increasing
2     123.501363  108.894245  119.889167  130.884089  Decreasing
3     124.510914  109.785449  120.763500  131.741551  Increasing
4     127.876074  110.372516  121.720167  133.067817  Increasing
         Date   AAPL.Open   AAPL.High    AAPL.Low  AAPL.Close  AAPL.Volume  \
0  2015-02-17  127.489998  128.880005  126.919998  127.830002     63152400
1  2015-02-18  127.629997  128.779999  127.449997  128.720001     44891700
2  2015-02-19  128.479996  129.029999  128.330002  128.449997     37362400
3  2015-02-20  128.619995  129.500000  128.050003  129.500000     48948400
4  2015-02-23  130.020004  133.000000  129.660004  133.000000     70974100

   AAPL.Adjusted          dn        mavg          up   direction
0     122.905254  106.741052  117.927667  129.114281  Increasing
1     123.760965  107.842423  118.940333  130.038244  Increasing
2     123.501363  108.894245  119.889167  130.884089  Decreasing
3     124.510914  109.785449  120.763500  131.741551  Increasing
4     127.876074  110.372516  121.720167  133.067817  Increasing

In [17]:
#for skipping bad lines use skip_bad_lines=False,bad lines means rows having data not fitting in any column

In [22]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',dtype={'rating':'int'})

C:\Users\ASUS\anaconda3\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: invalid value encountered in cast
  chunks = self._reader.read_low_memory(nrows)

ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 3

In [24]:
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv"

# Example 1: Parse a single column as dates
df = pd.read_csv(url, parse_dates=["Date"])
print(df.dtypes)   # 'Date' will now be datetime64[ns]

Date             datetime64[ns]
AAPL.Open               float64
AAPL.High               float64
AAPL.Low                float64
AAPL.Close              float64
AAPL.Volume               int64
AAPL.Adjusted           float64
dn                      float64
mavg                    float64
up                      float64
direction                object
dtype: object

In [25]:
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv"


# Example 2: Convert the 'Date' column into a custom format string
df2 = pd.read_csv(url, converters={"Date": lambda x: x.replace("-", "/")})
print(df2.head())

# Example 3: Apply a custom transformation (e.g., uppercase text)
# Suppose the CSV had a 'Company' column
df3 = pd.read_csv(url, converters={"Company": lambda x: x.upper()})

         Date   AAPL.Open   AAPL.High    AAPL.Low  AAPL.Close  AAPL.Volume  \
0  2015/02/17  127.489998  128.880005  126.919998  127.830002     63152400
1  2015/02/18  127.629997  128.779999  127.449997  128.720001     44891700
2  2015/02/19  128.479996  129.029999  128.330002  128.449997     37362400
3  2015/02/20  128.619995  129.500000  128.050003  129.500000     48948400
4  2015/02/23  130.020004  133.000000  129.660004  133.000000     70974100

   AAPL.Adjusted          dn        mavg          up   direction
0     122.905254  106.741052  117.927667  129.114281  Increasing
1     123.760965  107.842423  118.940333  130.038244  Increasing
2     123.501363  108.894245  119.889167  130.884089  Decreasing
3     124.510914  109.785449  120.763500  131.741551  Increasing
4     127.876074  110.372516  121.720167  133.067817  Increasing

In [27]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',na_values=['-'])

,name,release_year,rating,votes,genre
sno,,,,,
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [30]:
dfs=pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genre'],index_col='sno',chunksize=100)

In [45]:
for chunks in dfs :
    print(chunk.shape)

## Json files

In [46]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [47]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.0387
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.6690
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.8800
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,3.9800
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,2.5200
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.1810
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.1990
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.2670
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-30,1774828801,0.2670

# SQL files

In [48]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 5.0 MB/s eta 0:00:03
     ----------- ---------------------------- 3.4/11.9 MB 11.7 MB/s eta 0:00:01
     --------------- ------------------------ 4.7/11.9 MB 8.7 MB/s eta 0:00:01
     ------------------ --------------------- 5.5/11.9 MB 7.7 MB/s eta 0:00:01
     ----------------------- ---------------- 6.8/11.9 MB 7.8 MB/s eta 0:00:01
     -------------------------- ------------- 7.9/11.9 MB 7.1 MB/s eta 0:00:01
     ---------------------------- ----------- 8.4/11.9 MB 6.5 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 6.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 6.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 5.9 MB/s  0:00:02
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=4186638f848cc0d9b7ee8d86979c2ffb54c0b0a21528a4819149ba0f40639b20
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ASUS\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ASUS\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ASUS\anaconda3\Lib\site-packages)

In [49]:
import mysql.connector

In [50]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [53]:
df = pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8256\3653681956.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM city",conn)

DatabaseError: Execution failed on sql 'SELECT * FROM city': 1146 (42S02): Table 'world.city' doesn't exist